dist: xenial

jobs:
  include:
    - stage: build and push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - make build
      - make push

    - stage: deploy RC
      script:
        - make deploy server=instance.evarun.ru password=$USER_PASSWORD dbname=rc_sr2020
      on:
        branch: rc
