replicaCount: 1

app:
  port: 80
  catalog: sr2020-backup
  aws:
    region: eu-north-1

postgres:
  host: postgres
  port: 5432

image:
  backup:
    repository: sr2020/krohobor
    tag: dev
    pullPolicy: Always
  cron:
    repository: xordiv/docker-alpine-cron
    tag: latest
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
