replicaCount: 1

app:
  postgres:
    db: postgres

image:
  repository: postgres
  tag: 11.7
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5432

resources:
  limits:
    cpu: 100m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 512Mi
