apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: "{{ .Values.image.backup.repository }}:{{ .Values.image.backup.tag }}"
              imagePullPolicy: {{ .Values.image.backup.pullPolicy }}
              args:
                - /bin/sh
                - -c
                - krohobor dump create
              env:
                - name: KROHOBOR_CONFIG
                  value: /configs/config.yaml
              volumeMounts:
                - name: config
                  mountPath: "/configs"
                  readOnly: true
          volumes:
            - name: config
              secret:
                secretName: {{ .Release.Name }}-krohobor-secret
                items:
                  - key: config-secret.yaml
                    path: config.yaml
