alter table cyberdeck
    owner to backend;
alter table ic_instance
    owner to backend;
alter table node_link
    owner to backend;
alter table subnode
    owner to backend;
alter table software
    owner to backend;
alter table node_icon
    owner to backend;
alter table icon_file
    owner to backend;
alter table icon_api
    owner to backend;
alter table icon_portal
    owner to backend;
