alter table metatype_feature  owner to backend;
alter table general_feature  owner to backend;
alter table build_gf  owner to backend;
alter table build_mf  owner to backend;
alter table feature  owner to backend;
alter table implant  owner to backend;
alter table pill  owner to backend;
alter table drone  owner to backend;
alter table reagent  owner to backend;
