name: CI

on: [push]

jobs:
  deploy_rc:
    if: github.ref == 'refs/heads/rc'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$CONFIG" > .env'
        shell: bash
        env:
          CONFIG: ${{secrets.CONFIG}}
      - run: make migrate url=${{secrets.DB_URL}}/rc_sr2020

  deploy_production:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: 'echo "$CONFIG" > .env'
        shell: bash
        env:
          CONFIG: ${{secrets.CONFIG}}
      - run: make migrate url=${{secrets.DB_URL}}/sr2020
